### ISSUE TITLE
Inputs problem

### ISSUE THREAD

**Issue by sk8er000** [dshadoff/MiSTer_PCE-SNAC#1]
I've just assembled a PCB and the dpad is not recognized, the strange part is that when another button is pressed (without pressing any direction) the other button is recognized together with a direction (one for each button).
A regular USB snac is working with the same mister setup

**Comment by dshadoff** [comment]
That sounds like a short or an incomplete circuit... from your description, it would be related to the "Select" line from the SNAC into the PC Engine.

Suspects include the USB connector, pullup resistors R1 or R2, pins 2&3 into IC4, IC4 itself (including power), pins 6&7 out of IC4, and the mini-DIN8.

Check continuity along these paths, and ensure that they aren't shorted to any of: Gnd, 3V3 supply, or 5V supply.

The reverse path sounds OK.

**Comment by dshadoff** [comment]
Also check that:
- pins 1 & 5 of IC4 are getting 3v3 properly
- pin 4 is grounded, and
- pin 8 is getting 5V

**Comment by sk8er000** [comment]
Thank you for the answer I'll try to triple check everything again. Could it be related to some faulty component or other?
I've checked all the PCB components but it seems everything ok. 
With regular SNAC (tried both USB and HDMI version) the PCE adapter is working fine, so it shouldn't be a I/O board issue..
I can try to assemble a second PCB to see if there is a similar behaviour. On the actual PCB I can't notice anything suspicious..it seems like the signals on the same remains tied together and can't be properly recognized.
Here's a couple of pics of my PCB:
![IMG_20211126_143549](https://user-images.githubusercontent.com/35069659/143659620-7d91262f-9755-4d17-a2e0-37194972b7a1.jpg)
![IMG_20211126_143556](https://user-images.githubusercontent.com/35069659/143659646-bcab4156-2914-4353-b7e4-1de387cb3238.jpg)

**Comment by dshadoff** [comment]
Well, appearance looks OK, but you really need to do some continuity testing... looking at the board doesn't always show you all the possible problems.

The SELECT line is driven from the SNAC port, and passes via the USB connector into IC4, which does a level-shift, and then sends it out the PCE DIN socket.  SELECT tells the PCE controller whether to send back D-pad information, or the buttons.  Somehow it seems to be jammed on your board.  This could be due to an open circuit, or a short - so that the SELECT line's actual level never makes it to the controller.

One class of issue would be "open circuit", where a solder joint isn't correct.  This doesn't *appear* to be the case, but you can only be certain with continuity testing between the input pin (before the solder connection to the board) and the output pin (after the solder connection from the board).  This could also be the case if IC4 had a problem.  You might want to double-check pins 6 and 7 on IC4; they're hard to see clearly, but the solder joint might not be perfect there.

The second class of issues would be either "short to ground" or "short to power supply".  This could be a case where two adjacent pins are soldered together.  This doesn't *appear" to be the case, from your pictures but occasionally this can happen underneath a chip or a resistor.  This problem could also manifest if the pullup resistor was the wrong value (too low).

So, it's a case of checking the everything which should be connected is actually connected, and that everything which should be kept disconnected remains disconnected.  If you have an oscilloscope, you should be able to check the waveforms at the entrance to IC4 and the exit from IC4.  The "CLR" signal should toggle once every 1/60th of a second while playing a game, and the "SELECT" signal should toggle 5 times in a brief period when the CLR signal transitions.

**Comment by sk8er000** [comment]
While I was trying to debug the problem I noticed that signals weren't as described. Fortunately the issue was very obvious.. probably I was distracted while assembling the PCB and soldered R1 and R2 wrong (90° rotated). Sorry to bothered you
